apiVersion: auto.gke.io/v1
kind: AllowlistSynchronizer
metadata:
  name: istio-ambient
spec:
  projectNumber: 560780937444745
  bucketName: agentic-allowlist
  allowlistPaths:
    - istio/1.30.4/istio-cni.yaml
    - istio/1.30.4/istio-ztunnel.yaml
