#!/usr/bin/env bash
# 63-allowlist-install.sh — authorise and install the Autopilot WorkloadAllowlists
# generated by 62-istio-allowlists.sh.
#
# This is the step that makes privileged workloads admissible on Autopilot, and
# it is four things in a fixed order. Getting the order wrong is why this took a
# day the first time:
#
#   1. Upload the allowlists to Cloud Storage. The GKE service agent reads them,
#      not you, so it needs access to the bucket. infra/tofu/modules/storage
#      grants that; this script verifies it rather than assuming.
#
#   2. Add the paths to the MANAGED ORG POLICY
#      container.managed.autopilotPrivilegedAdmission. A cluster's
#      --autopilot-privileged-admission value must be drawn from this policy's
#      allowPaths, so the policy comes first. This is ORGANISATION-scoped: it
#      affects every cluster in the org, not just Autopilot ones.
#
#   3. Set the paths on the cluster. Takes about 20 minutes. The FIRST attempt
#      after writing the policy is usually refused with CUSTOM_ORG_POLICY_DENIED
#      because the policy has not propagated. That is not a misconfiguration, so
#      this script waits and retries rather than failing.
#
#   4. Install the AllowlistSynchronizer, which is the only way a
#      WorkloadAllowlist can enter the cluster. You cannot kubectl apply one.
#
# Idempotent. Safe to re-run: it skips the cluster update when the paths already
# match, which is what makes it usable in a rebuild chain.
set -uo pipefail
SD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SD/lib.sh"
load_env
assert_universe

ISTIO_VERSION="${ISTIO_VERSION:-1.30.4}"
ALLOWLIST_DIR="$LAB_ROOT/istio-ambient/allowlists"
# Prefix, not individual files. A directory prefix means a future Istio version
# bump needs no org policy change and no 20-minute cluster update. Individual
# file paths were what we used first and it cost an update every time.
BUCKET="${ALLOWLIST_BUCKET:-}"
PREFIX="istio/${ISTIO_VERSION}"

require gcloud kubectl

step "Resolving the allowlist bucket"
if [[ -z "$BUCKET" ]]; then
  BUCKET="$(tofu_out allowlist_bucket 2>/dev/null || true)"
fi
if [[ -z "$BUCKET" ]]; then
  BUCKET="$(gcloud storage ls 2>/dev/null | sed 's|gs://||; s|/$||' | grep -m1 'allowlist' || true)"
fi
[[ -n "$BUCKET" ]] || die "could not determine the allowlist bucket.
    Set ALLOWLIST_BUCKET, or apply infra/tofu (module.storage creates it)."
ok "bucket: gs://$BUCKET"

# The synchroniser reads as the GKE service agent. Without this grant it reports
# an error that reads like an org policy problem.
step "Checking the GKE service agent can read the bucket"
AGENT="service-${PROJECT_NUMBER:?PROJECT_NUMBER not set in .env.local}@container-engine-robot.${UNIVERSE_PREFIX:-eu0}-system.iam.gserviceaccount.com"
if gcloud storage buckets get-iam-policy "gs://$BUCKET" --format=json 2>/dev/null \
   | grep -q "$AGENT"; then
  ok "service agent has access"
else
  warn "granting roles/storage.admin to the GKE service agent"
  gcloud storage buckets add-iam-policy-binding "gs://$BUCKET" \
    --member="serviceAccount:${AGENT}" --role=roles/storage.admin >/dev/null 2>&1 \
    && ok "granted" || die "could not grant bucket access to $AGENT"
fi

step "Uploading the allowlists"
UPLOADED=()
for f in "$ALLOWLIST_DIR"/istio-*.yaml; do
  [[ -s "$f" ]] || continue
  base="$(basename "$f")"
  gcloud storage cp "$f" "gs://${BUCKET}/${PREFIX}/${base}" >/dev/null 2>&1 \
    && { ok "$base"; UPLOADED+=("${PREFIX}/${base}"); } \
    || die "upload failed for $base"
done
[[ "${#UPLOADED[@]}" -gt 0 ]] || die "no allowlists to upload in $ALLOWLIST_DIR.
    Run 62-istio-allowlists.sh first."

step "Managed organization policy"
ORG="${ORG_NUMBER:?ORG_NUMBER not set in .env.local}"
POLICY_FILE="$LAB_ROOT/istio-ambient/orgpolicy-autopilot-privileged-admission.yaml"
DIR_PATH="gs://${BUCKET}/${PREFIX}/"

# allowAnyGKEPath MUST stay true. Setting it false makes cluster creation and
# update fail across the whole organisation unless every cluster passes a
# conforming flag. Refuse to write a policy that would do that.
cat > "$POLICY_FILE" <<YAML
# Generated by 63-allowlist-install.sh. Organisation-scoped: this affects every
# GKE cluster in the org, not only Autopilot ones.
#
# allowAnyGKEPath: true keeps the default authorisation of every GKE partner and
# approved open-source allowlist. Setting it false breaks cluster creation
# org-wide unless each cluster passes a conforming
# --autopilot-privileged-admission. Do not change it.
name: organizations/${ORG}/policies/container.managed.autopilotPrivilegedAdmission
spec:
  rules:
    - enforce: true
      parameters:
        allowAnyGKEPath: true
        allowPaths:
          - ${DIR_PATH}
YAML
grep -q 'allowAnyGKEPath: true' "$POLICY_FILE" \
  || die "refusing to apply a policy without allowAnyGKEPath: true"

CURRENT_POLICY="$(gcloud org-policies describe \
  container.managed.autopilotPrivilegedAdmission --organization="$ORG" \
  --effective --format=json 2>/dev/null || true)"
if echo "$CURRENT_POLICY" | grep -q -- "$DIR_PATH"; then
  ok "org policy already authorises $DIR_PATH"
  POLICY_CHANGED=0
else
  gcloud org-policies set-policy "$POLICY_FILE" >/dev/null 2>&1 \
    && ok "org policy set: $DIR_PATH" \
    || die "could not set the org policy. This needs orgpolicy.policyAdmin."
  POLICY_CHANGED=1
fi

step "Authorising the paths on the cluster"
CLUSTER="${CLUSTER_NAME:-agentic}"
REGION="${UNIVERSE_REGION:?}"
# gke://* must be listed explicitly. Setting this flag REPLACES the default
# authorisation of all GKE-managed allowlists rather than adding to it.
WANT="gke://*,${DIR_PATH}"
HAVE="$(gcloud container clusters describe "$CLUSTER" --location "$REGION" \
  --format='value(autopilot.privilegedAdmissionConfig.allowlistPaths)' 2>/dev/null \
  | tr -d "[]'" | tr ';' ',' | tr -d ' ')"

if [[ "$HAVE" == *"$DIR_PATH"* ]]; then
  ok "cluster already authorises $DIR_PATH (skipping the 20-minute update)"
else
  # A policy written seconds ago has not propagated, and the update is refused
  # with FAILED_PRECONDITION / CUSTOM_ORG_POLICY_DENIED. Identical command
  # succeeds a couple of minutes later. Retry rather than fail.
  [[ "$POLICY_CHANGED" -eq 1 ]] && { log "waiting 120s for org policy propagation"; sleep 120; }
  UPDATED=0
  for attempt in 1 2 3 4; do
    log "cluster update attempt $attempt (this takes ~20 minutes)"
    if gcloud container clusters update "$CLUSTER" --location "$REGION" \
         --autopilot-privileged-admission="$WANT" 2>/tmp/allowlist-update.err; then
      UPDATED=1; break
    fi
    if grep -q 'CUSTOM_ORG_POLICY_DENIED' /tmp/allowlist-update.err; then
      warn "refused by org policy; almost certainly propagation. Waiting 120s."
      sleep 120
      continue
    fi
    warn "cluster update failed for a reason other than propagation:"
    sed 's/^/    /' /tmp/allowlist-update.err >&2
    break
  done
  [[ "$UPDATED" -eq 1 ]] || die "could not authorise the allowlist paths on $CLUSTER"
  ok "cluster authorises $DIR_PATH"
fi

step "Installing the AllowlistSynchronizer"
kube_context >/dev/null 2>&1 || true
assert_kube_reachable
# allowlistPaths here are object paths WITHIN the bucket, no gs:// prefix. The
# full gs:// URLs belong in the org policy and the cluster flag.
{
  echo "apiVersion: auto.gke.io/v1"
  echo "kind: AllowlistSynchronizer"
  echo "metadata:"
  echo "  name: istio-ambient"
  echo "spec:"
  echo "  projectNumber: ${PROJECT_NUMBER}"
  echo "  bucketName: ${BUCKET}"
  echo "  allowlistPaths:"
  for p in "${UPLOADED[@]}"; do echo "    - ${p}"; done
} > "$LAB_ROOT/istio-ambient/allowlistsynchronizer.yaml"
kubectl apply -f "$LAB_ROOT/istio-ambient/allowlistsynchronizer.yaml" >/dev/null 2>&1 \
  || die "could not apply the AllowlistSynchronizer"

for _ in $(seq 1 24); do
  N="$(kubectl get workloadallowlists --no-headers 2>/dev/null | wc -l | tr -d ' ')"
  [[ "$N" -ge "${#UPLOADED[@]}" ]] && break
  sleep 10
done
N="$(kubectl get workloadallowlists --no-headers 2>/dev/null | wc -l | tr -d ' ')"
if [[ "$N" -ge "${#UPLOADED[@]}" ]]; then
  ok "$N WorkloadAllowlists installed"
  kubectl get workloadallowlists 2>/dev/null | sed 's/^/    /' >&2
else
  warn "only $N of ${#UPLOADED[@]} allowlists installed. Synchroniser status:"
  kubectl describe allowlistsynchronizer istio-ambient 2>/dev/null \
    | sed -n '/Status/,$p' | head -20 | sed 's/^/    /' >&2
  die "allowlist installation incomplete. A path error here is usually the
    bucket grant; a Failed phase is usually the org policy."
fi

step "Done"
log "next: ./scripts/64-istio-ambient.sh"
