#!/usr/bin/env bash
# derive-images.sh — regenerate infra/helm/images.txt by RENDERING every chart
# in infra/helm/charts.txt and extracting the real image references.
#
# Why this exists: GCD's Artifact Registry has no remote or virtual
# repositories, so there is no pull-through mirror and every image must be
# pushed by hand. Getting that list wrong means a half-installed platform with
# ImagePullBackOff pods and no obvious cause. Guessing repository paths from
# product names is how that happens, so we render instead.
#
# The Solo charts live in a PUBLIC Google Artifact Registry on public GCP, so
# this needs the public-GCP account, not the universe one. That is the one place
# in this repo where talking to googleapis.com is correct.
#
# Usage:
#   scripts/derive-images.sh            # write infra/helm/images.txt
#   scripts/derive-images.sh --diff     # show what would change, write nothing
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

DIFF_ONLY=0
[[ "${1:-}" == "--diff" ]] && DIFF_ONLY=1

MANIFEST="infra/helm/charts.txt"
TARGET="infra/helm/images.txt"
[[ -f "$MANIFEST" ]] || { echo "error: $MANIFEST not found" >&2; exit 1; }

command -v helm >/dev/null || { echo "error: helm not installed" >&2; exit 1; }

# ── auth against the Solo public chart registry ──────────────────────────────
# The charts under us-docker.pkg.dev/solo-public are public, but Helm's OCI
# client still presents a bearer token on pull, so this login is not optional.
PUBLIC_ACCOUNT="${SOLO_GCP_ACCOUNT:-tom.orourke@solo.io}"
echo "==> helm registry login us-docker.pkg.dev (as $PUBLIC_ACCOUNT, public GCP)"

# Primary path: ask gcloud. This fails if the active configuration is the
# universe one and the public account's token is not in the live credential db,
# which is the normal state in this repo.
TOKEN="$(gcloud auth print-access-token --account="$PUBLIC_ACCOUNT" 2>/dev/null || true)"

# Fallback: mint one directly from the legacy authorized_user credential gcloud
# leaves on disk. Public-GCP refresh tokens are long-lived, unlike the universe's
# WIF tokens, so this usually works even when everything else has expired.
if [[ -z "$TOKEN" ]]; then
  LEGACY="$HOME/.config/gcloud/legacy_credentials/${PUBLIC_ACCOUNT}/adc.json"
  if [[ -f "$LEGACY" ]]; then
    echo "    gcloud declined; minting from $LEGACY"
    TOKEN="$(python3 - "$LEGACY" <<'PYTOK'
import json, sys, urllib.parse, urllib.request
d = json.load(open(sys.argv[1]))
data = urllib.parse.urlencode({
    "client_id": d["client_id"], "client_secret": d["client_secret"],
    "refresh_token": d["refresh_token"], "grant_type": "refresh_token",
}).encode()
try:
    r = urllib.request.urlopen(
        urllib.request.Request("https://oauth2.googleapis.com/token", data=data), timeout=20)
    print(json.load(r)["access_token"])
except Exception:
    pass
PYTOK
)"
  fi
fi

if [[ -z "$TOKEN" ]]; then
  echo "error: no valid credentials for $PUBLIC_ACCOUNT on public GCP." >&2
  echo "       run: gcloud auth login --account=$PUBLIC_ACCOUNT" >&2
  echo "       note this is deliberately NOT the universe account: the Solo" >&2
  echo "       charts live in a public Google Artifact Registry, so this is the" >&2
  echo "       one place in the repo where talking to googleapis.com is correct." >&2
  exit 1
fi
printf '%s' "$TOKEN" | helm registry login -u oauth2accesstoken --password-stdin us-docker.pkg.dev

TMP="$(mktemp)"
ERRLOG="$(mktemp)"
FAILED=()
trap 'rm -f "$TMP"' EXIT

{
  echo "# Images to mirror into the in-universe Artifact Registry before any Helm install."
  echo "#"
  echo "# GENERATED by scripts/derive-images.sh from infra/helm/charts.txt on $(date -u '+%Y-%m-%d')."
  echo "# Do not hand-edit: change charts.txt and re-run. Every entry below was"
  echo "# extracted from a rendered chart, not guessed from a product name."
  echo "#"
  echo "# GCD has no remote/virtual Artifact Registry repos, so there is no"
  echo "# pull-through mirror: every line here gets pushed by"
  echo "# scripts/mirror-images.sh."
  echo
} >"$TMP"

render_and_extract() {
  local ref="$1" version="$2" ns="$3"; shift 3
  local name; name="$(basename "$ref")"

  local out
  if [[ "$ref" == *"|"* ]]; then
    # repo-style: <chart>|<repo-url>
    local chart="${ref%%|*}" repo="${ref#*|}"
    out="$(helm template "$chart" "$chart" --repo "$repo" --version "$version" \
            -n "$ns" --include-crds "$@" 2>>"$ERRLOG")" || return 1
  else
    out="$(helm template "$name" "$ref" --version "$version" \
            -n "$ns" --include-crds "$@" 2>>"$ERRLOG")" || return 1
  fi

  # Require a NON-EMPTY value after `image:`. CRD charts embed bare `image:`
  # keys inside OpenAPI schema properties (field definitions, not images), and
  # without this they pollute the list with blanks.
  printf '%s' "$out" \
    | grep -oE '^[[:space:]]*-?[[:space:]]*image:[[:space:]]*"?[A-Za-z0-9][^"[:space:]]*"?' \
    | sed -E 's/.*image:[[:space:]]*"?//; s/"?$//' \
    | grep -vE '^\{\{|^$' \
    | grep -E '[./]' \
    | sort -u || true
  # `|| true` matters: the script runs under `set -o pipefail`, so a grep that
  # matches nothing would fail the whole pipeline and make a legitimately
  # image-free CRDs chart look like a render failure.
}

while IFS= read -r line; do
  line="${line%%#*}"; line="$(echo "$line" | xargs || true)"
  [[ -z "$line" ]] && continue

  # `image <ref>` lines are pinned directly, no chart to render.
  if [[ "$line" == image\ * ]]; then
    printf '%s\n' "${line#image }" >>"$TMP"
    continue
  fi

  # Split off any `| <extra helm args>` suffix. Several Solo Enterprise charts
  # refuse to render without their required values (license key, enabled
  # products, OIDC client ids), so charts.txt carries render-only placeholders.
  EXTRA=""
  if [[ "$line" == *"|"*" --"* || "$line" == *" | "* ]]; then
    EXTRA="${line#*|}"; line="${line%%|*}"
    line="$(echo "$line" | xargs)"
  fi

  read -r ref version ns <<<"$line"
  ns="${ns:-default}"
  echo "==> rendering $ref ($version)"
  # shellcheck disable=SC2086
  if imgs="$(render_and_extract "$ref" "$version" "$ns" $EXTRA)"; then
    if [[ -n "$imgs" ]]; then
      { echo; echo "# --- $(basename "${ref%%|*}") $version"; printf '%s\n' "$imgs"; } >>"$TMP"
      printf '    %s image(s)\n' "$(wc -l <<<"$imgs" | xargs)"
    else
      # A *-crds chart contains only CustomResourceDefinitions, so zero images
      # is the correct answer, not a failure. Anything else with no images is
      # suspicious and worth flagging.
      case "$ref" in
        *-crds|*crds) printf '    0 images (CRDs only — expected)\n' ;;
        *) echo "    rendered but produced NO images — check this"; FAILED+=("$ref $version (no images)") ;;
      esac
    fi
  else
    echo "    FAILED to render"
    FAILED+=("$ref $version")
  fi
done <"$MANIFEST"

echo
if (( ${#FAILED[@]} )); then
  echo "WARNING: ${#FAILED[@]} chart(s) failed to render:" >&2
  printf '  %s\n' "${FAILED[@]}" >&2
  echo "  A 403 usually means the chart version does not exist; a 401 means the" >&2
  echo "  login expired; an 'execution error at' means the chart needs a required" >&2
  echo "  value, which belongs after the | in charts.txt." >&2
  echo "  Verbatim helm output: $ERRLOG" >&2
  grep -E '^Error' "$ERRLOG" | sort -u | sed 's/^/    /' >&2 || true
fi

TOTAL="$(grep -cvE '^\s*(#|$)' "$TMP" || true)"
echo "==> $TOTAL image(s) derived"

if (( DIFF_ONLY )); then
  diff -u "$TARGET" "$TMP" || true
else
  cp "$TMP" "$TARGET"
  echo "==> wrote $TARGET"
  echo "    next: scripts/derive-images.sh --diff to review, then"
  echo "          poc/2026-09-agentic-platform/scripts/15-mirror-images.sh"
fi
